### ISSUE TITLE
KLExperiment.listen() callback fail

### ISSUE THREAD

**Issue by jmwmulle** [jmwmulle/klibs#1]
So in the file KLExperiment.py there's a method, listen(), which is supposed to be the primary method for receiving input.

It's come to pass so frequently that things need to be changing during the period for which a response is being listened for, I'd added:
a) a `wait_callback` argument;
b) a `wait_cb_args` argument; and
c) a `wait_cb_kwargs` argument

The functionality starts to show up at `line 623`. It doesn't appear elsewhere in the method; the statements you see are all there are.

But I made a few serious oversights.

1) This dilemma is something to note, but not actually my primary problem unless it's *causing* the primary problem. This "callback" always returns it's result as the result of the `listen()` method itself if it returns a value when it's called. This was fucking. retarded. of me—if I *do* want to return `None`, `False`, or `0` I can't, and if I *don't* want to end the `listen()` just because something happened during the callback, I can't. Seriously, seriously stupid.

2) But, at the moment, the real problem is that *every* time a `wait_callback` is provided, the program beachballs. In the example experiment I included in the e-mail, the first time this happens is actually during the `KLEyelink.py` method that checks for gaze boundaries. `KLEyelink.drift_correct()` is where this will appear to show up; a function is defined within it at `line 120` that gets passed as the `wait_callback` arg. Even *this* beach-balls and I don;t know why—it;s something I recently changed because it didn't used to, but I can;t find it.

The final goal, though, is at `line 1381` of `experiment.py` (ie. not KLIBS but the actual experiment i'm writing). That execution of `listen()` should be updating the mask as per the "gaze coordinates" [read: mouse position, for the time being]. It used to be able to do this, before I made masks that worked. Then I made masks that worked and so my code deliberately set me up to fail as part of it's conspiratorial contrivances to drive me insane.

This may be the part where bug reports and alcohol are no longer supposed to interact...

**Comment by Random-Word** [comment]
MWE:

```
#!/usr/bin/env python

import time

start_time = time.time()

def listen(wait_callback, *args, **kwargs):
    while True:
        try:
            wait_resp = wait_callback(*args, **kwargs)
            if wait_resp:
                return [wait_resp, time.time() - start_time]
        except Exception as e:
            raise RuntimeError("Wait_callback failed with following message: {0}".format(e.message))

def test():
    def dc(dc_location, dc_gaze_boundary):
        print(dc_location, dc_gaze_boundary)
        return dc_location+dc_gaze_boundary
    return listen(dc, 1, 2)

print(test())
```

Bug is not in the callback concept, but something in your specific callback (dc, line 120 of https://github.com/jmwmulle/klibs/blob/master/klibs/KLEyeLink.py).

Close at leisure.
